### PR TITLE
Generate accessors for scalar types, array of scalars and scalars in struct in the sail state

### PR DESCRIPTION
**Pull request by julienfreche**
Hello Sail maintainers,

As discussed, here is a patch that modifies the generate c2 code to be able to hook into reads and writes to the sail state variables. The idea is to create getter/setter functions declared as static inline in the header file. Functionally,  this change should be a no-op and by itself (without manual modification) it's still not enough to expose an API but it is the first step in that direction.

Goals for this patch; create r/w accessors for:
- scalar types in sail_state
- scalars in structures in the sail_state
- vector of scalars

Non-goals for this patch:
- Handle all possible types (GMP integers, etc..). We can take care of this in future patches. For my current experiments and goals, adding those variables is not required/not a high priority for now.
- Provide a configuration/option for the user to specify what accessors should be generated and what accessors will be provided by an external entity (in that case only the accessor signature can be generated). This will come in future patches to not add too much logic all at once.

The patch is tested against the ARM model and produces an emulator that is working.

### CODE REVIEW

**Comment by julienfreche** [comment]
Thank you!

**Comment by Alasdair** [comment]
There was a small bug in one of the tests in tests/c with a missing is_api_ctyp guard. I just pushed a small change that fixed it.

**Comment by julienfreche** [comment]
I see! The fix makes sense. What is the best way to run the tests for c2?

**Comment by Alasdair** [comment]
There's a little python script in test/c/run_tests.py (although it's still python 2 because that's what our jenkins server has)

It runs with lots of different combinations of options but you could comment out the lines other than
```
xml += test_c2('unoptimized C', '', '', True)
```
if you just want to run with the -c2 flag

**Comment by julienfreche** [comment]
Great, that's helpful! thank you very much

**Pull request merged**
