### PR TITLE
Float: Cleanup unnecessary include files.

### PR DESCRIPTION
**Pull request by Incarnation-p-lee**

### CODE REVIEW

**Review by jordancarlin — APPROVED** [review]
Looks like a good cleanup.

I also wonder if the float `interface.sail` file really needs to include `<float/arith_internal.sail>` or if that should be dropped.

**Comment by Incarnation-p-lee** [comment]
> really needs to in

Yes, that make sense to me, and updated.

**Comment by Incarnation-p-lee** [comment]
Kindly Reminder, ;)!

**Comment by Alasdair** [comment]
Have been away the last week, will take a look on Monday

**Comment by Incarnation-p-lee** [comment]
> Have been away the last week, will take a look on Monday

Never mind, take your time.

**Pull request merged**
