### PR TITLE
Add struct patterns

### PR DESCRIPTION
**Pull request by Alasdair**
Allow pattern matching on structs, i.e.

```
match struct_value {
    struct { field1 = <pattern>, field2 = <pattern> } => ...
}
```

can simplify `field1 = field1` to just `field1` like when constructing records

Currently all fields must be present, not sure whether to relax this or having some syntax like:

```
struct { field1 = <pattern>, _ }
```

for partial matches

### CODE REVIEW

**Comment by Alasdair** [comment]
@bacam I'm not sure how pattern matching on records looks like in Coq (I assume you can though?), so I haven't implemented that yet.

**Comment by Alasdair** [comment]
Rust (which has very similar pattern matching syntax) uses '..' to ignore fields, i.e. `struct { field = <pattern>, .. }`

**Comment by bacam** [comment]
I'll take a look at how to do it in Coq.  At worst I think a desugered version should work.

**Comment by bacam** [comment]
I'll force push a properly formatted version in a moment.

**Comment by Alasdair** [comment]
Thanks!

**Comment by nwf-msr** [comment]
Will these new patterns work in `mapping`s or just `match` expressions?

**Comment by Alasdair** [comment]
I haven't implemented them for mappings yet, but it should be fairly straightforward

**Comment by Alasdair** [comment]
I ran into a fun bug when constant folding struct literals in some tests. We might want to allow optionally including struct names like:
```
struct Name { field1 = ..., field2 = ... }
```
That way the type-checker could insert them, and later passes would have an easier time inferring the type of structs. I think the Rust-ish syntax of just `Name { field1 = ... }` would also be unambiguous, but it might be a bit strange to have that and also allow defining structs without their names like we do now.

**Pull request merged**
