### PR TITLE
Use SPDX-License-Identifier: BSD-2-Clause instead of full text

### PR DESCRIPTION
**Pull request by arichardson**
This makes the header at the top of each file a lot shorter.

### CODE REVIEW

**Comment by arichardson** [comment]
I did not touch the few cases of BSD-3-Clause, just the common header at the top of each non-contrib file.

**Comment by arichardson** [comment]
All done with simple search+replace (using 6 different patterns since the column width was different in various files)

**Comment by Alasdair** [comment]
Looks nice, I do like pull requests that are: "+260 −5,686" 😃 

I think the CI failure is probably some kind of storage failure on github's end, hopefully it'll go away by re-running.

**Comment by Alasdair** [comment]
Last failure is just the line number in some expected test output has changed due to the header size changing. There's a script `test/typecheck/update_errors.sh` or I could fix it after merging.
```
Failed: diff fail/prelude_no_order.error fail/prelude_no_order.expect
stdout:
5,6c5,6
<   | :51.0-22:
<   | 51 |$include <vector.sail>
---
>   | :72.0-22:
>   | 72 |$include <vector.sail>
```

**Comment by arichardson** [comment]
> Last failure is just the line number in some expected test output has changed due to the header size changing. There's a script `test/typecheck/update_errors.sh` or I could fix it after merging.
> 
> ```
> Failed: diff fail/prelude_no_order.error fail/prelude_no_order.expect
> stdout:
> 5,6c5,6
> <   | :51.0-22:
> <   | 51 |$include <vector.sail>
> ---
> >   | :72.0-22:
> >   | 72 |$include <vector.sail>
> ```

Ah I didn't think this would affect tests so I didn't bother runnign them. Let me fix that quickly.

**Comment by arichardson** [comment]
> > Last failure is just the line number in some expected test output has changed due to the header size changing. There's a script `test/typecheck/update_errors.sh` or I could fix it after merging.
> > ```
> > Failed: diff fail/prelude_no_order.error fail/prelude_no_order.expect
> > stdout:
> > 5,6c5,6
> > <   | :51.0-22:
> > <   | 51 |$include <vector.sail>
> > ---
> > >   | :72.0-22:
> > >   | 72 |$include <vector.sail>
> > ```
> 
> Ah I didn't think this would affect tests so I didn't bother runnign them. Let me fix that quickly.

Looks like that was the only issue and CI is happy now.

**Comment by arichardson** [comment]
ping?

**Pull request merged**
