### PR TITLE
Fix type check errors for scattered mapping uses before the final clause

### PR DESCRIPTION
**Pull request by jrtc27**
This test was giving the following error:

      Type error:
      [test/c/scattered_mapping.sail]:12:23-44
      12 |function unit_str () = unit_str_map_forwards(())
         |                       ^-------------------^
         | No val spec found for unit_str_map_forwards
         |

This is because we were erroneously putting the realised val specs next to their function definitions, which are put in the place of the final clause (as a result of descattering), so once we strip the mapping val spec itself, subsequent type checks will fail. Instead, put them in place of the mapping val spec, or not at all if it does not exist. This also removes the need for remove_mapping_valspecs.

### CODE REVIEW

**Comment by jrtc27** [comment]
We ran into this in sail-riscv/sail-cheri-riscv trying to make `csr_name_map` a scattered mapping so that we could add CHERI clauses.

**Comment by Alasdair** [comment]
Thanks!
Are you sure the remove_mapping_valspecs rewrite that lem and coq are using isn't required? I get errors trying to build the lem for sail-riscv.
I have a branch (poly_mappings) lying around that rewrites and simplifies a lot of this code while also allowing polymorphic mappings that should also fix this issue, but it's currently languishing a bit and needs some extra work before it can be merged.

**Comment by jrtc27** [comment]
What error are you getting, and trying to build what? I can build `riscv_coq` and `riscv_rmem`, as well as `generated_definitions/lem/RV64/riscv.lem`, just fine. The rewrite should be completely pointless as realise_mappings will have already realised each one (the pattern being matched is exactly the same, just with bindings).

**Comment by Alasdair** [comment]
I get `Type error: specified variable already defined as a top-level variable binding: spc_forwards` when going from Lem to Isabelle. The generated code contains:
```
val spc_forwards : unit -> string

val spc_forwards : unit -> string
```
Looking into it I think it's because spc_forwards and friends are defined like:
```
val spc     : unit <-> string

val spc_forwards : unit -> string
function spc_forwards () = " "
val spc_backwards : string -> unit
function spc_backwards s = ()
```
So I guess the remove_val_specs thingy was trying to remove the 'val spc' to prevent this duplication? If you are thinking *Eww that's gross*... I agree 100% I've been working to turn it into
```
mapping spc : token(" +") <-> unit = {
  forwards x if string_match(" +", x) => (),
  backwards () => " "
}
```
but until then we have to have a horrible hack in the type system that allow duplicate val-specs to enable this.

**Comment by jrtc27** [comment]
Ah I see, there were no mapping clauses before so no val specs were introduced. It looks like the forwards/backwards specs can just be removed though; a mapping val spec automatically implicitly defines those.

**Comment by Alasdair** [comment]
That does work for the forwards and backwards functions but I think there ends up being a similar problem with some of the helpers like:
```
val spc_matches_prefix : string -> option((unit, nat))
```
Realizing the mappings then removing any duplicates that have been introduced would work. It's probably what we should do.

**Comment by jrtc27** [comment]
Updated to only keep the first val spec with a given identifier.

**Comment by jrtc27** [comment]
(Though for what it's worth, you should also be able to drop the `spc_matches_prefix` val spec from the input, that's implied by the mapping too)

**Comment by Alasdair** [comment]
I had to merge manually due to https://github.com/rems-project/sail/commit/23f605252180f0bb5d9a1fbed05f4c5dad14e7ec let me know if there are issues

**Pull request closed without merging**
