### PR TITLE
Remove trailing whitespace and fix typos

### PR DESCRIPTION
**Pull request by nazar-codethink**

### CODE REVIEW

**Comment by Alasdair** [comment]
Would be better to fix typos in a smaller PR I think. It would be cleaner if we didn't have trailing whitespace, but I don't think we want to create spurious merge conflicts by removing it everywhere.

**Comment by nazar-codethink** [comment]
How is erroneous whitespace different from typos? Fixing whitespace along with actual functionality results in commits that are hard to read - like [this](https://github.com/rems-project/sail/commit/e92d957c8e39263169ff11fe31dba9c7a922baf1).  Also note that there's git option to ignore whitespace conflicts - https://stackoverflow.com/questions/9776527/merging-without-whitespace-conflicts

Are you sure you don't want to rip this band-aid off?

**Comment by nazar-codethink** [comment]
I'll close this PR as there seems to be no interest in this

**Comment by Alasdair** [comment]
I manually fixed most of the comment typos you found in https://github.com/rems-project/sail/commit/dd3466e09b3702bcfc807c210e6de210472b2db9 and https://github.com/rems-project/sail/commit/913fc0db23a56dd66327d02d0e3f4b56d8df749e so thank you for taking the time to find them!

**Pull request closed without merging**
