### PR TITLE
Add static to more C functions

### PR DESCRIPTION
**Pull request by arichardson**
This allows me to compile sail-riscv64 and sail-riscv128 code in the same
static library.

### CODE REVIEW

**Comment by Alasdair** [comment]
I'm not sure we should have static in c_codegen.ml

I've been re-factoring and improving the code generator recently, and to avoid breaking any existing users I copied the code from c_backend.ml into a new file (c_codegen.ml) where I can make breaking changes. It generates a separate sail.h and sail.c file and uses them as a library in sail_emu.c, rather than generating just a big c file with everything. Currently this uses the `-c2` flag, so if you aren't using that you don't have to worry about changing anything in c_codegen.ml.

**Comment by arichardson** [comment]
I'll revert the c_codegen changes. I made those because I wasn't sure what needs changing so I just added static everywhere.

I am currently using the C code to compare the sail-cheri-riscv against my manually written CHERI decompression library here:
https://github.com/CTSRD-CHERI/cheri-compressed-cap/blob/master/test/regen_sail_c_code.sh

Once this works, I can try using the -c2 mode.

**Comment by arichardson** [comment]
I've reverted the codegen.ml changes, and with these changes I can link both generated files into the same library.

**Comment by Alasdair** [comment]
We definitely need to use the !opt_static flag to control if we add static to model_init and model_fini, otherwise the sail-riscv emulator doesn't build - maybe also in the other places it's been added.
```
/usr/bin/ld: /tmp/riscv_sim_RV64.C1l4Eu.ltrans0.ltrans.o: in function `main':
/home/alasdair/sail-riscv/c_emulator/riscv_sim.c:492: undefined reference to `model_init'
collect2: error: ld returned 1 exit status
```
Could maybe add a little helper function like
```
let static () = if !opt_static then "static " else ""
```
to allow `printf "%s..." (static ()) ...` and reduce the duplication

**Pull request merged**
