### PR TITLE
Ocamlformat

### PR DESCRIPTION
**Pull request by Alasdair**
Created a .ocamlformat config, and formatted all the source

Need to check if it's done anything bad to any toplevel definitions

### CODE REVIEW

**Comment by bacam** [comment]
This is quite aggressive at removing whitespace, particularly losing vertically aligned comments and grouping in `.mli` files (it feels like they're imposing the limitations of ocamldoc on the source text).  It also has the usual pretty printer problem of falling apart at large AST patterns/expressions.

I'm not sure there's anything better to be done with these though - I don't see any options to control this stuff.

**Comment by PeterSewell** [comment]
Thibaut had a config for readdwarf that seemed ok to me

**Comment by Alasdair** [comment]
read dwarf has 

doc-comments=before

which should fix some of the comment issues I think, but there are a few places where our doc comments are just attached to the wrong thing right now I think. I think this might just be an OCaml parsing thing though, and not strictly ocamldoc, as OCaml attributes also usually have to be postfix

**Comment by Alasdair** [comment]
`module-item-spacing=preserve` might also be good

**Comment by bacam** [comment]
The `module-item-spacing=preserve` option preserves the grouping I was talking about, which is nice.

**Pull request closed without merging**
