### PR TITLE
Float: Refactor the test data to avoid duplication

### PR DESCRIPTION
**Pull request by Incarnation-p-lee**
* Add new file to hold all test data.
* Leverage the test data instead of hard code for testing.

### CODE REVIEW

**Review by jordancarlin — APPROVED** [review]

**Comment by Incarnation-p-lee** [comment]
Hi @Alasdair 
Is there any suggestion about how to compare the bits('n) as unsigned int in sail? I suppose that we will have something like overload `<` in vector.sail or something else like bits('n) to int.

Please feel free to correct me if any misunderstanding. Or I can help to cover that pat if doesn't exit for now.

**Comment by Incarnation-p-lee** [comment]
> Hi @Alasdair Is there any suggestion about how to compare the bits('n) as unsigned int in sail? I suppose that we will have something like overload `<` in vector.sail or something else like bits('n) to int.
> 
> Please feel free to correct me if any misunderstanding. Or I can help to cover that pat if doesn't exit for now.

Any suggestion for vector compare?

**Comment by bacam** [comment]
It's quite common to do things like `unsigned v < unsigned w`, but maybe providing direct unsigned and signed comparisons for bitvectors would be helpful for the SMT and SystemVerilog backends?

**Comment by rmn30** [comment]
The risc-v spec defines signed and unsigned operators (e.g. `<_u` and `<_s` ) for this: https://github.com/riscv/sail-riscv/blob/0b8935ee518ed97ea284c36addcfbee5b119ca76/model/prelude.sail#L117 . It would be easy to replace the implementations with builtins if Sail provided them.

**Comment by Incarnation-p-lee** [comment]
Thanks for the information. Totally agree that we can provide one direct comparation if it dosen't exist for now, would like to wait the final confirmation from @Alasdair before we start the actual work.

**Comment by Alasdair** [comment]
Yes, the way to go is to convert to signed or unsigned integers and then compare those.

**Comment by Incarnation-p-lee** [comment]
Thanks a lot, Alasdair. To make sure that the bits size of 16, 32, 64, and 128 can be converted to unsigned/signed for comparison. If so I think that is good enough, or we may need to add compare ops to vector.sail?

**Comment by Alasdair** [comment]
The integer types are arbitrary precision, so yes you can convert any bitvector size into them.

**Comment by Incarnation-p-lee** [comment]
Oh, Great! Thanks a lot, really saved my day!

**Pull request merged**
