### PR TITLE
Lean: Added the lean tests to the automated tests

### PR DESCRIPTION
**Pull request by lfrenot**

### CODE REVIEW

**Comment by bacam** [comment]
Note that `test/run_tests.sh` is the big set of tests that you get when you manually run tests, it isn't the tests in the CI.

**Comment by lfrenot** [comment]
Oh
Should I add the tests to the CI? And in that case, where can I change that?

**Comment by bacam** [comment]
`test/run_core_tests.sh` (and remove it from the other one, because it includes the core tests).

**Comment by lfrenot** [comment]
Thank you

**Comment by Alasdair** [comment]
I think it should be in `test/run_coverage_tests.sh`

The tests in `run_core_tests.sh` are run by the build matrix job which tests the builds on a bunch of platforms. The job that runs as many tests as possible and generates the code coverage report and the comment on the PRs like above is the `run_coverage_tests.sh` script.

**Comment by bacam** [comment]
Yes, what Alasdair said - I got the github actions confused.

**Comment by lfrenot** [comment]
Oh, thank you
I also need to add it back to `run_tests.sh`, right? It looks like it has tests in common with `run_coverage_tests.sh`

**Comment by bacam** [comment]
Yes, that'd be fine.  (I probably ought to deduplicate them.)

**Pull request merged**
